### ISSUE TITLE
Provider Component Support: ecs

### ISSUE THREAD

**Issue by roleyfoley** [hamlet-io/engine-plugin-azure#30]
The [ecs](https://github.com/codeontap/gen3/blob/10d3201d9facc1c39cde697893ad7840ef78d942/providers/shared/components/ecs/id.ftl) component currently offers container based application hosting using docker based images and the [Amazon ECS](https://aws.amazon.com/ecs/) container orchestration service 

The component itself creates an autoscaling group of virtual machines which have docker installed on them by default along with an ECS cluster. Each virtual machine registers with the ECS cluster to offer its compute services to the cluster 

There are two subcomponents which manage the deployment of the application. 

The **service** subcomponent which ensures that a given number of instances of a docker container ( including environment configuration)  run across the cluster at any given time. This ensures that the application is always active 

The **task** subcomponent deploys a task definition ( environment configuration and a link to a docker container image ) which can be invoked on demand through a CodeOnTap Jenkins server or through  a cron based scheduled managed as part of the task deployment 

Multiple services and tasks can live on the same cluster 

The docker based images used by the services and tasks are stored in a private registry which is deployed during the application build process 

This component should provide a basic container orchestration service which is closely integrated with the cloud provider. Kubernetes or a similar level of functionality would be considered a separate component at this stage

**Comment by RossMurr4y** [comment]
Azure has two primary services for container instantiation - Azure Container Instances, and Azure Kubernetes Service.

Container Instances is intended for simple, self-contained containers and its per-second billing model suggests it is fairly closely aligned not with the Hamlet `ECS` component but with the `task` ECS-subcomponent.

> Azure Container Instances is a great solution for any scenario that can operate in isolated containers, including simple applications, task automation, and build jobs. For scenarios where you need full container orchestration, including service discovery across multiple containers, automatic scaling, and coordinated application upgrades, we recommend Azure Kubernetes Service (AKS).

> Azure Container Instances enables a layered approach to orchestration, providing all of the scheduling and management capabilities required to run a single container, while allowing orchestrator platforms to manage multi-container tasks on top of it.

If the Azure plugin were to implement the `ECS` component without Kubernetes I don't feel the result would reflect the definitions of the Hamlet component/subcomponents. Because Azure expect you to bring your own orchestrator when using Container Instances, autoscaling could not be implemented here short of Azure suddenly supporting it or monkey-patching in a 3rd party tool. On the flipside, AKS pretty closely aligns with the component and subcomponent definitions. If we draw the line at not implementing Helm Charts yet, then we should be able to implement the `ECS` component in the Azure provider as intended, making full use of the autoscaling capabilities of AKS without delving into much (if any) Kubernetes DSL.

@roleyfoley do you think this works?

**Comment by roleyfoley** [comment]
Yeah I'd probably go towards AKS as the Azure equivalent of our ECS component.  ACI sounds like it could be used in a similar way to fargate is used with in AWS, a container orchestration service (ECS) calls the Fargate API to a get a container hosted somewhere. 

When you say not implementing helm charts are you saying BYO helm charts or us generating the helm charts.?

**Comment by RossMurr4y** [comment]
@roleyfoley more just not interacting with them at all as a part of the first pass of the component.

**Comment by RossMurr4y** [comment]
Replaced by #192 #193
